# Generated by Django 4.1.1 on 2022-12-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFuneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDifunto', models.CharField(max_length=100)),
                ('cedulaDifunto', models.IntegerField()),
                ('fechaEntierro', models.DateField()),
                ('lugarEntierro', models.CharField(max_length=100)),
                ('fechaVelacion', models.DateField()),
                ('lugarVelacion', models.CharField(max_length=100)),
                ('tipoUsuario', models.CharField(choices=[(1, 'Cotizante'), (2, 'Beneficiario')], default=0, max_length=20)),
                ('cedulaUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.usuario')),
            ],
        ),
    ]
