# Generated by Django 4.0.6 on 2022-09-17 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedulaBeneficiario', models.IntegerField(unique=True)),
                ('nombreBeneficiario', models.CharField(max_length=100)),
                ('apellidoBeneficiario', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(blank=True, max_length=250, null=True)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('cuota', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('cedulaCotizante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.cotizante')),
            ],
        ),
        migrations.DeleteModel(
            name='Documentaciones',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodoPago',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='idPlan',
        ),
        migrations.AddField(
            model_name='factura',
            name='fechaPago',
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='factura',
            name='totalDeuda',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='factura',
            name='totalPago',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='plan',
            name='caracteristicas',
            field=models.CharField(max_length=1000, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.AddField(
            model_name='pagos',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.factura'),
        ),
        migrations.AddField(
            model_name='cotizante',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.plan'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cedulaCotizante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nuevavida.cotizante'),
        ),
    ]
