# Generated by Django 4.1.1 on 2022-12-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefuneral',
            name='cedulaDifunto',
        ),
        migrations.RemoveField(
            model_name='detallefuneral',
            name='nombreDifunto',
        ),
        migrations.RemoveField(
            model_name='detallefuneral',
            name='tipoUsuario',
        ),
    ]
