# Generated by Django 4.1.1 on 2022-12-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0002_remove_detallefuneral_ceduladifunto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefuneral',
            old_name='cedulaBeneficiario',
            new_name='idBeneficiario',
        ),
    ]
