# Generated by Django 4.0.6 on 2022-09-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0002_beneficiario_cotizante_pagos_delete_documentaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='deuda',
        ),
        migrations.AddField(
            model_name='cotizante',
            name='deuda',
            field=models.IntegerField(null=True),
        ),
    ]
