# Generated by Django 4.0.6 on 2022-09-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0003_remove_pagos_deuda_cotizante_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizante',
            name='deuda',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
