# Generated by Django 4.1.1 on 2022-12-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0003_rename_cedulabeneficiario_detallefuneral_idbeneficiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefuneral',
            old_name='idBeneficiario',
            new_name='idbeneficiario',
        ),
    ]
