# Generated by Django 4.1.1 on 2022-12-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0005_rename_idbeneficiario_detallefuneral_cedubeneficiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefuneral',
            old_name='cedubeneficiario',
            new_name='idbeneficiario',
        ),
    ]
