# Generated by Django 4.1.1 on 2023-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0006_rename_cedubeneficiario_detallefuneral_idbeneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefuneral',
            name='tipo',
            field=models.CharField(choices=[('c', 'Cotizante'), ('b', 'Beneficiario')], default='c', max_length=100),
        ),
    ]
