# Generated by Django 4.1.1 on 2023-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuevavida', '0007_detallefuneral_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefuneral',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
